### ISSUE TITLE
Observaciones generales

### ISSUE THREAD

**Issue by tomasdelvechio** [SebaJuarez/Mancala#15]
Mirando [este método](https://github.com/SebaJuarez/Mancala/blob/a2e20f732da99e2e99380193807bbf5f8663fd4a/src/ar/edu/unlu/mancala/controlador/MancalaController.java#L73) veo algunos problemas:

 1. El primer parámetro es el modelo, pero no lo usas en ninguna parte. Porque? Que pasó ahí?
 2. ¿Es necesario que ese actualizar maneje tantas situaciones? ¿No puede haber varios controllers, o en su defecto, varios actualizar diferentes? ¿O al menos, en el if principal se derive a sub-métodos del tipo `actualizarPartida`, `actualizarMovimiento`, etc...?
 3. Este tipo de cosas:
```java
if (mancala.getJugadoresEnPartida().contains(this.jugador)) {
	if (mancala.getPartida().getUltimoEnMover().equals(this.jugador)) {
		vista.informar("movimiento realizado!");
	} else {
		vista.informar("su rival movio!");
	}
}
```
no podrían ser reemplazadas por métodos de mayor abstracción como:
```java
if (mancala.jugadorEnPartida(this.jugador)) {
	if (mancala.movioUltimo(this.jugador)) {
		vista.informar("movimiento realizado!");
	} else {
		vista.informar("su rival movio!");
	}
}
```

4. Ejemplos de código y su contraparte como me las imagino yo:

```java
# obtener ultimo jugador
Jugador ultimoJugador = mancala.getJugadoresEnPartida()
						.get(mancala.getJugadoresEnPartida().size() - 1);

# consultar si un jugador está en la partida
mancala.getJugadoresEnPartida().contains(this.jugador)
```

```java
Jugador ultimoJugador = mancala.getUltimoJugador();
// o al menos
Jugador ultimoJugador = mancala.getJugador(mancala.getJugadoresEnPartida().size()); // la posición la maneja internamente el otro objeto, sino siempre vas a estar atado a una List de Java.

# consultar si un jugador está en la partida
mancala.estaJugador(this.jugador)

```

5. Una de dos, si exponemos la logica interna del objeto, al menos retornalo arriba de todo y lo usas tranquilamente:

`listaJugadores = mancala.getJugadoresEnPartida();`

porque sino estas siempre haciendo esas llamadas.

6. Por otro lado, este case:

![image](https://github.com/SebaJuarez/Mancala/assets/1976584/9a267826-4848-426b-9f03-97226054d507)

Es necesario que la vista sea tan escueta? no podríamos pasarle la lista de ganadores y el jugador actual (this.jugador) y que la vista haga los ifs para mostrar empate y si el jugador de la vista es perdedor o ganador???

Lo que te pongo acá aplica al resto del código, creo que esta bien el juego pero seguís con estos temas mas procedurales. Hay un tema con la delegación de responsabilidades.

**Comment by SebaJuarez** [comment]
Muchas gracias por la revisión. Te contesto punto por punto lo que realicé.

1) Recuerdo hacer el controlador copiando la idea del video del ejemplo de chat que estaba en el aula, en ese video utilizaba el modelo que tenía de atributo y no el que le pasaba por parámetro. Podría plantearme hacer que devuelva algún objeto del modelo según se requiera. Desde que lo hice en su momento nunca mas me lo replantee. 

2),3),4),5) Estos puntos ya los tenia contemplado, es más ya lo tengo implementado de una forma muy parecida a lo que me estás sugiriendo. Estas cuestiones eran a lo que me refería en el mail sobre "ordenar el código y pulirlo". 
Por eso te pregunte si me dabas el OK del modelo para poder seguir, solamente me centre en reestructurar y rehacer el modelo lo mas rápido posible, no me centre en acomodar el controlador por las dudas que me hagas una corrección grande del modelo.

6) Mi idea era que la vista tenga la menor lógica posible. Podría delegar responsabilidad a la vista, pero como te había dicho, no me puse a pensar en mas nada que el modelo por el momento.

**Comment by tomasdelvechio** [comment]
De 1 a 5 estamos ok, si no empezaste, dale para adelante que va bien.

Respecto a 6., podemos discutirlo un poco mas, pero quería aclararte una cosa acá: Cuando nosotros decimos que la vista debería tener poca lógica, en general tratamos de decir que debería tener poca lógica DE NEGOCIO. La vista debería tener todas las responsabilidades vinculadas a como se va a mostrar la información, sea mucha o poca lógica. No estoy diciendo que no lo entiendas, pero quería que quede claro por las dudas.

Dicho eso, te tomo parte de la critica. Es verdad que eso no va en la vista, pero tampoco en el controller donde está actualmente. Para mi, determinar este estado de finalización es del modelo. Luego, el controlador debería preguntarle a algún objeto del modelo (la Partida tal vez?) si fue empate o no y ahí llamar a la vista con los métodos correspondientes. Lo que me hace ruido es que determinar si hubo empate o no este en el controlador (toda la parte del `.size() > 1`).

**Comment by tomasdelvechio** [comment]
Despues veo alguna cosas mas pero no quiero abundar demasiado. Por ejemplo:

https://github.com/SebaJuarez/Mancala/blob/main/src/ar/edu/unlu/mancala/vista/grafica/VistaGrafica.java#L30

En esa linea estas creando un objeto, que eventualmente podría no usarse y que solo se usará al finalizar la partida. Similar con los atributos cartelGanador, cartelPerdedor...

Esos objetos no se podrían instanciar en el momento de ser utilizados, y no en la construcción de la Vista? Se entiende?

**Comment by SebaJuarez** [comment]
Buenas, pude hacerme un tiempo para retomar. Si bien cada vez que me pongo a repasar el código surge algún detalle nuevo, creo que a grandes rasgos solucione los problemas de responsabilidad que tenía. El mayor cambio lo hice en el controlador, ya que los dividí en dos. Uno para toda la lógica del jugador (log-in  y persistencia en general) y el otro para la partida (creación, movimiento etc..).  Para mantener el encapsulamiento y que los controladores solamente puedan "controlar" su parte de la lógica, dividí el modelo y la vista en interfaces que solamente atiendan las necesidades de su parte (partida o jugador). De esta manera solamente están atados a controlar el flujo que les pertenece controlar. 
Con respecto a la vista y la lógica, le agregue un poco de lógica (poner el lado del jugador al frente, mostrar el cartel cuando finaliza la partida según el estado de finalización del mismo (ganó, perdió o empató) -> ahora lo decide el modelo), pero puede que mi implementación sea un poco mas cercana a MVP que MVC, esta charla la tuvimos con uno de los profesores un dia en la materia.

duda:
Mi mayor duda es en las clases responsables del movimiento, si me podes dar el feedback de esa clase en particular me quedaría mas tranquilo.

También tengo una duda en los metodos default que hice en algunas interfaces, bajo mi punto de vista están bien aplicados, le aporta mucha flexibilidad a las interfaces, pero no se ustedes si aceptan este tipo de implementaciones (podrían decirme que podía usar una clase abstracta).

**Comment by tomasdelvechio** [comment]
Miremos las dos clases de movimiento:

![image](https://github.com/SebaJuarez/Mancala/assets/1976584/9b920a8f-7d3c-4682-a61d-f8c2451d0599)

Así a ojo, son MUY parecidas, salvo por las partes que están relacionadas al sentido. 

Sin sentarme a codearlo, casi que veo una interfaz ISentidoMovimiento que compone al Movimiento (que sería una sola clase) y es la nueva interfaz la que tiene 2 objetos que la implementan: SentidoHorario y SentidoAntihorario

En cada uno de los objetos, un método hace lo que corresponda, y la clase Movimiento es instanciada pasandole en el constructor el sentido (que pasa a ser obligatorio para generar la instancia de movimiento).

¿Que métodos tendrían que implementar estos ISentidosMovimiento?

- convertirSentidoMovimiento(partida.getTablero(), jugadorMueve) donde cada sentido retorna la Queue con su politica correspondiente
- getAgujeros() que obtiene una lista de agujeros en el orden que corresponde iterarlos.

Acá me tengo que detener un rato otra vez. Sigo sin entender la necesidad que tenes de manejar los indices. No entiendo porque en lugar de iterar los indices con un while no podes hacer un foreach de los agujeros y hacer un break cuando te quedas sin habas. No lo entiendo. Tenes un List<Agujero>. Iteralo directo, sin indice, ni nada.

Creo que en general esta bien y estamos hilando fino, con contar lo que venís haciendo va a salir todo bien. Pero quería marcarte esto una vez mas.

**Comment by tomasdelvechio** [comment]
No te respondí sobre usar código en las interfaces.

Para mí es polémico, porque justamente una interfaz da idea de API, no de implementación. Dicho eso, si el lenguaje lo permite, no te puedo culpar por usarlo. 

Pero si necesitamos ese tipo de extensión, es posible que estemos en un escenario de herencia, clase abstracta o inyección de dependencias.

**Comment by SebaJuarez** [comment]
Excelente, esa era la vuelta de rosca que me faltaba dar.  Ya pude implementarlo y es mucho mas fácil y práctico de esta manera. Gracias!!
